const words = [
    'bubblegum',
    'river',
    'popcorn',
    'revolver',
    'magic',
    'potato',
    'blockhead',
    'loophole',
    'ambidextrous',
    'fish',
    'nineteen',
    'clover',
    'beeswax',
    'cereal',
    'chameleon',
    'lightbulb',
    'gibberish',
    'serpent',
    'gamble',
    'bunny',
    'doorman',
    'amateur',
    'jigsaw',
    'cultish',
    'bamboo',
    'bumblebee',
    'pumpkin',
    'harmonica',
    'haircut',
    'jellyfish',
    'quarrelsome',
    'fax machine',
    'fairies',
    'rhyme',
    'embarrassing',
    'pajamas',
    'duffel bag',
    'overpriced',
    'ketchup',
    'koala',
    'panther',
    'flower',
    'squishmallow',
    'synesthesia',
    'tempestuous',
    'falafel',
    'pedestrian',
    'dennis rodman',
    'basketball',
    'rainforest',
    'meow',
    'dentures',
    'helen keller',
    'persian',
    'kitten',
    'pirate',
    'eggnog',
    'facetious',
    'lettuce',
    'mate',
    'pancake',
    'fork',
    'soup',
    'wine',
    'wolverine',
    'lovebird',
    'shoe lace',
    'drawer',
    'peanuts',
    'fake flowers',
    'chocolate',
    'credit card',
    'sofa',
    'sarong',
    'tracksuit',
    'juicy jacket',
    'poncho',
    'tankini',
    'sunroof',
    'sundress',
    'bambi',
    'cocoa',
    'butter',
    'carousel',
    'stargazing',
    'honey',
    'marinade',
    'fossils',
    'somersault',
    'trampoline',
    'libra',
    'aquarius',
    'rainbow',
    'gemini',
    'scorpio',
    'capricorn',
    'book fair',
    'hopskotch',
    'sugar',
    'blacklight',
    'sugarfree',
    'pluto',
    'froth',
    'tulips',
    'sandy',
    'bunkbed',
    'chinatown',
    'tortilla',
    'parking lot',
    'baby blue',
    'racoon',
    'valet',
    'princess',
    'peach',
    'televisions',
    'christmas',
    'goth',
    'cameo',
    'forgot',
    'angel',
    'cacti',
    'fire hydrant',
    'shadow',
    'dry cleaning',
    'fingertips',
    'cocoon',
    'soccer',
    'cassette',
    'matador',
    'jungle',
    'tiger',
    'darling',
    'wink',
    'smiles',
    'monsoon',
    'cowboy',
    'shark',
    'safari',
    'moroccan',
    'lemonade',
    'limeade',
    'mockingbird',
    'luna',
    'suave',
    'madame',
    'jet ski',
    'speedo',
    'matzo ball',
    'lollipop',
    'spanish',
    'french',
    'pebble',
    'name tag'
];

export default words;